db.dropDatabase()
// USERS
db.pokerDB.users.insert([
	{_id:"userId_0", username:"user0", password:"user0", email: "user0@pp.com", isGlobalAdmin: false, loginCount:0, lastLoginDate:-1,
		 roomACL: [ {roomId: "roomId_0", role: "admin"}, {roomId: "roomId_1", role: "member"}]},
	{_id:"userId_1", username:"user1", password:"user1", email: "user1@pp.com", isGlobalAdmin: false, loginCount:0, lastLoginDate:-1,
		 roomACL: [ {roomId: "roomId_0", role: "member"}, {roomId: "roomId_1", role: "viewer"}]},
	{_id:"userId_2", username:"user2", password:"user2", email: "user2@pp.com", isGlobalAdmin: false, loginCount:0, lastLoginDate:-1,
		 roomACL: [ {roomId: "roomId_0", role: "member"} ]},
	{_id:"userId_3", username:"user3", password:"user3", email: "user3@pp.com", isGlobalAdmin: false, loginCount:0, lastLoginDate:-1,
		 roomACL: [ {roomId: "roomId_0", role: "member"} ]},
	{_id:"userId_4", username:"user4", password:"user4", email: "user4@pp.com", isGlobalAdmin: false, loginCount:0, lastLoginDate:-1,
		 roomACL: [ {roomId: "roomId_0", role: "member"}, {roomId: "roomId_2", role: "admin"}]},
	{_id:"userId_5", username:"user5", password:"user5", email: "user5@pp.com", isGlobalAdmin: false, loginCount:0, lastLoginDate:-1,
		 roomACL: [ {roomId: "roomId_0", role: "viewer"}, {roomId: "roomId_2", role: "member"}]}		 
])
//ROLES
db.pokerDB.roles.insert([
	{role:"admin", mask: "01010101"},
	{role:"member", mask: "01010101"},
	{role:"viewer", mask: "01010101"},
	{role:"leader", mask: "01010101"}
])
// ROOMS
db.pokerDB.rooms.insert([
	{_id:"roomId_0", name:"Room 0", roomConfig: {public: true, maxGames: -1}},
	{_id:"roomId_1", name:"Room 1", roomConfig: {public: true, maxGames: -1}},
	{_id:"roomId_2", name:"Room 2", roomConfig: {public: true, maxGames: -1}},
	{_id:"roomId_3", name:"Room 3", roomConfig: {public: true, maxGames: -1}}
])
// GAMES
db.pokerDB.games.insert([
	{_id:"gameId_0", 
		roomId:"roomId_0",
		name:"Game 0", 
		tags: ["g0_tag0", "g0_tag1"], 
		gameConfig: { closed: false, timer: -1},
		itemCollectionId: 0,
		inviteeIds:["userId0", "userId1", "userId2", "userId3"], 
		playerIds:["userId1", "userId3"],
		leaderId: "userId4", 
		status: "Open", 
		timer: -1, 
		archived: false},
	{_id:"gameId_1", 
		roomId:"roomId_0",
		name:"Game 1", 
		tags: ["g1_tag0", "g1_tag1"],
		gameConfig: { closed: false, timer: -1},
		itemCollectionId: 0,
		inviteeIds:["userId1","userId2","userId3"], 
		playerIds:["userId2","userId3"],
		leaderId: "userId5", 
		status: "Open", 
		timer: -1, 
		archived: false},
	{_id:"gameId_2", 
		roomId:"roomId_1",
		name:"Game 2", 
		tags: ["g2_tag0", "g2_tag1"], 
		gameConfig: { closed: false, timer: -1},
		itemCollectionId: 0,
		inviteeIds:["userId0", "userId1", "userId3"], 
		playerIds:["userId1", "userId3"],
		leaderId: "userId5", 
		status: "Open", 
		timer: -1, 
		archived: false},
])
// ITEMS
db.pokerDB.items.insert([
	{_id:"itemId_0", 
		gameId:"gameId_0",
		title: "Item title 0",
		lastEstimate: 2,
		lastRoundId: "roundId_0",
		unit: "storyPoint",
		descUrl: "http://jira.firstbest.com/browse/UMS-2312",
		rounds: ["roundId_0", "roundId_1"]
	},
	{_id:"itemId_1", 
		gameId:"gameId_0",
		title: "Item title 1",
		lastEstimate: 4,
		lastRoundId: "roundId_3",
		unit: "storyPoint",
		descUrl: "http://jira.firstbest.com/browse/UMS-2322",
		rounds: ["roundId_2", "roundId_3"]
	},
	{_id:"itemId_3", 
		gameId:"gameId_1",
		title: "Item title 3",
		lastEstimate: 2,
		lastRoundId: "roundId_4",
		unit: "storyPoint",
		descUrl: "http://jira.firstbest.com/browse/UMS-2112",
		rounds: ["roundId_4"]
	},
	{_id:"itemId_4", 
		gameId:"gameId_1",
		title: "Item title 4",
		lastEstimate: null,
		lastRoundId: null,
		unit: "storyPoint",
		descUrl: "http://jira.firstbest.com/browse/UMS-2324",
		rounds: []
	}
])
// ROUNDS
db.pokerDB.rounds.insert([
	{_id:"roundId_0",
		itemId: "itemId_0",
		gameId:"gameId_0",
		unit: "storyPoint",
		startTime: -1,
		endTime: -1,
		elapsedTime: -1,
		estimate: 2,
		voteStats: {avg: 0, min: 0, max: 0},
		votes: [ {playerId: "userId_0", vote: 3, timestamp: 0},
				 {playerId: "userId_1", vote: 2, timestamp: 0},
				 {playerId: "userId_2", vote: 2, timestamp: 0}
				],
	},
	{_id:"roundId_1",
		itemId: "itemId_0",
		gameId:"gameId_0",
		unit: "storyPoint",
		startTime: -1,
		endTime: -1,
		elapsedTime: -1,
		estimate: 3,
		voteStats: {avg: 0, min: 0, max: 0},
		votes: [ {playerId: "userId_0", vote: 3, timestamp: 0},
				 {playerId: "userId_1", vote: 2, timestamp: 0},
				 {playerId: "userId_3", vote: 2, timestamp: 0}
				],
	},
		{_id:"roundId_2",
		itemId: "itemId_1",
		gameId:"gameId_0",
		unit: "storyPoint",
		startTime: -1,
		endTime: -1,
		elapsedTime: -1,
		estimate: 2,
		voteStats: {avg: 0, min: 0, max: 0},
		votes: [ {playerId: "userId_0", vote: 3, timestamp: 0},
				 {playerId: "userId_1", vote: 2, timestamp: 0},
				 {playerId: "userId_3", vote: 2, timestamp: 0}
				],
	},
	{_id:"roundId_3",
		itemId: "itemId_1",
		gameId:"gameId_0",
		unit: "storyPoint",
		startTime: -1,
		endTime: -1,
		elapsedTime: -1,
		estimate: 3,
		voteStats: {avg: 0, min: 0, max: 0},
		votes: [ {playerId: "userId_0", vote: 3, timestamp: 0},
				 {playerId: "userId_1", vote: 2, timestamp: 0},
				 {playerId: "userId_3", vote: 2, timestamp: 0}
				],
	},
	{_id:"roundId_4",
		itemId: "itemId_4",
		gameId:"gameId_1",
		unit: "storyPoint",
		startTime: -1,
		endTime: -1,
		elapsedTime: -1,
		estimate: 3,
		voteStats: {avg: 0, min: 0, max: 0},
		votes: [ {playerId: "userId_0", vote: 3, timestamp: 0},
				 {playerId: "userId_1", vote: 2, timestamp: 0},
				 {playerId: "userId_3", vote: 2, timestamp: 0}
				],
	}
])
